<?php

namespace AdminBundle\Repository;

/**
 * JobPersonnalityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobPersonnalityRepository extends \Doctrine\ORM\EntityRepository
{
}
