<?php

namespace AdminBundle\Repository;

/**
 * QUESTIONRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
