<?php

namespace AdminBundle\Repository;

use AdminBundle\Entity\Question;

/**
 * QUESTIONRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Renvois toutes les questions
     *
     * @return array
     */
    public function getQuestions()
    {
        return $this->findAll();
    }

    /**
     * Renvois une question grâce à sont id
     *
     * @param $id
     *
     * @return null|object
     */
    public function getQuestionById($id)
    {
        return $this->findOneBy(['id' => $id]);
    }

    /**
     * Créer une question
     *
     * @param $label
     *
     * @return Question|bool
     */
    public function postQuestion($label)
    {
        if(!$this->checkIfQuestionAlreadyExist($label))
        {
            $em = $this->getEntityManager();

            $question = new Question();

            $question->setLabel($label);

            $em->persist($question);
            $em->flush();

            return $question;
        }

        return false;
    }

    /**
     * Modifie une question
     *
     * @param $id
     * @param $label
     *
     * @return null|object
     */
    public function putQuestion($id, $label)
    {
        $em = $this->getEntityManager();

        $question = $this->getQuestionById($id);
        $question->setLabel($label);

        $em->persist($question);
        $em->flush();

        return $question;
    }

    /**
     * Supprime une question
     *
     * @param $id
     */
    public function deleteQuestion($id)
    {
        $em = $this->getEntityManager();
        $question = $this->getQuestionById($id);

        $em->remove($question);
        $em->flush();
    }

    /**
     * Renvois true si la question existe déjà
     *
     * @param $label
     *
     * @return bool
     */
    public function checkIfQuestionAlreadyExist($label)
    {
        $isHereOrNot = $this->getEntityManager()->createQueryBuilder()
            ->select("q")
            ->from("AdminBundle:Question", "q")
            ->where("q.label = :label")
            ->setParameter(":label", $label)
            ->getQuery()
            ->getResult();

        if(count($isHereOrNot))
            return true;

        return false;
    }
}
