<?php

namespace AdminBundle\Repository;
use AdminBundle\Entity\Visitor;

/**
 * StatistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getVisitors()
    {
        return $this->findAll();
    }

    /**
     * @param $id
     * @return null|object
     */
    public function getVisitorById($id)
    {
        return $this->findOneBy(['id' => $id]);
    }

    /**
     * @param $ip
     * @return array
     */
    public function getVisitorByIp($ip)
    {
        $result = $this->findBy(['ip' => $ip]);

        if(count($result) === 1)
            return $result[0];

        return $result;
    }

    /**
     * @return mixed
     */
    public function getNumberOfConnectionByCountry()
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('v.country, count(v)')
            ->from('AdminBundle:Visitor', 'v')
            ->groupBy("v.country")
            ->getQuery()->getScalarResult();

    }

    public function getRegisteredYears()
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select("YEAR(v.connexionDate) as year")
            ->from("AdminBundle:Visitor", "v")
            ->groupBy("year")
            ->getQuery()->getResult();
    }

    public function getVisitorBy($string, $year)
    {
        $lower = strtolower($string);

        return $this->getEntityManager()->createQueryBuilder()
            ->select("$string(v.connexionDate) as $lower,count(v) as number")
            ->from("AdminBundle:Visitor", "v")
            ->where("YEAR(v.connexionDate) = $year")
            ->groupBy($lower)
            ->getQuery()->getScalarResult();
    }

    public function getBrowser()
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('v.browser, count(v)')
            ->from('AdminBundle:Visitor', 'v')
            ->groupBy("v.browser")
            ->getQuery()->getScalarResult();

    }

    public function getVisitorsWhoSharedAndThoseWhoDont()
    {
        $visitorWhoShared = $this->getEntityManager()->createQueryBuilder()
            ->select('count(v) as shared')
            ->from('AdminBundle:Visitor', 'v')
            ->where('v.hasShared = true')
            ->andWhere('v.hasCompleteTest = true')
            ->getQuery()->getSingleScalarResult();

        $visitorWhoDont = $this->getEntityManager()->createQueryBuilder()
            ->select('count(v) as notshared')
            ->from('AdminBundle:Visitor', 'v')
            ->where('v.hasShared = false')
            ->andWhere('v.hasCompleteTest = true')
            ->getQuery()->getSingleScalarResult();

        return ["Shared" => $visitorWhoShared, "DontShared" => $visitorWhoDont];
    }

    public function getVisitorsForQuizzInformation($param, $year)
    {
        if(!is_null($year))
        {
            $request = $this->getEntityManager()->createQueryBuilder()
                ->select('MONTH(v.connexionDate) as month, count(v) as number')
                ->from('AdminBundle:Visitor', 'v');

            if(is_null($param))
            {
                $request->where("v.hasCompleteTest is NULL");
            }
            else
            {
                $request->where("v.hasCompleteTest = $param");
            }

            return $request->andWhere(" YEAR(v.connexionDate) = $year")
                ->groupBy('month')
                ->getQuery()->getScalarResult();
        }
        else
        {
            return false;
        }
    }

    /**
     * @param $ip
     * @param $browser
     * @param $country
     * @param $connexionDate
     * @return Visitor|bool
     */
    public function postVisitor($ip, $browser, $country, $connexionDate)
    {
        if(!is_null($ip) && !is_null($browser) && !is_null($country) && !is_null($connexionDate))
        {
            $em = $this->getEntityManager();
            $visitor = new Visitor();

            $visitor->setIp($ip)
                ->setBrowser($browser)
                ->setConnexionDate($connexionDate)
                ->setCountry($country);

            $em->persist($visitor);
            $em->flush($visitor);

            return $visitor;
        }
        else
        {
            return false;
        }
    }

    /**
     * Permet de définir quand un visiteur à partager sont résultat
     *
     * @param $id
     * @return bool|object
     */
    public function setSharedToTrue($id)
    {
        if(!is_null($id))
        {
            $em = $this->getEntityManager();

            $visitor = $em->getRepository("AdminBundle:Visitor")->getVisitorById($id);

            if($visitor->getHasShared() !== true && !is_null($visitor))
            {
                $visitor->setHasShared(true);

                $em->persist($visitor);
                $em->flush();

                return $visitor;
            }

            return false;
        }

        return false;
    }

    /**
     * Permet de définir quand un visiteur à commencer/terminer le quizz
     *
     * @param $id
     * @param $bool
     * @return bool|object
     */
    public function setQuizzCompletion($id, $bool)
    {
        if(!is_null($id))
        {
            $em = $this->getEntityManager();

            $visitor = $em->getRepository("AdminBundle:Visitor")->getVisitorById($id);

            if($visitor->getHasCompleteTest() !== true  && !is_null($visitor))
            {
                $visitor->setHasCompleteTest($bool);

                $em->persist($visitor);
                $em->flush();

                return $visitor;
            }

            return false;
        }

        return false;
    }

}
